on:
  workflow_call:
    inputs:
      branch:
        required: false
        type: string

jobs:
  autobump:
    name: Autobump
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:

      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch }}

      - uses: kostrykin/autobump-action@v0.1
        id: autobump
        with:
          glob: |
            **/*.py
            **/*.md
            **/*.rst
            LICENSE

      - run: echo "<${{ steps.autobump.outputs.pull-request-url }}>" >> $GITHUB_STEP_SUMMARY
