on:
  workflow_call:

jobs:
  autobump:
    name: Autobump
    runs-on: ubuntu-latest

    permissions:
      contents: write
      pull-requests: write

    steps:

      - uses: actions/checkout@v4

      - uses: kostrykin/autobump-action@v0.1
        id: autobump
        with:
          glob: |
            **/*.py
            **/*.md
            **/*.rst

      - run: echo "<${{ steps.autobump.outputs.pull-request-url }}>" >> $GITHUB_STEP_SUMMARY
