on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      document_filename:
        required: true
        type: string
      sources:
        required: true
        type: string
      build_future_branches:
        required: true
        type: boolean

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{
        github.event_name == 'pull_request' ||
        github.ref_name == 'current' ||
        (inputs.build_future_branches && startsWith(github.ref_name, 'future/'))
      }}
    permissions:
      contents: write
    steps:

      - name: Initialize
        uses: actions/checkout@v4

      - uses: kostrykin/build-latex-document-action@v2.2.0
        with:
          working_directory: ${{ inputs.working_directory }}
          document_filename: ${{ inputs.document_filename }}
          sources: ${{ inputs.sources }}
