on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      document_filename:
        required: true
        type: string
      sources:
        required: true
        type: string
      build_future_branches:
        required: true
        type: boolean
      target_branch:
        type: string
        default: pdf

jobs:
  setup:
    name: Setup the target branch
    id: setup
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:

      - name: Initialize
        uses: actions/checkout@v4

      - name: Check existence of the target branch
        id: check_target_branch
        shell: bash
        run: |
          echo "ok=$(git ls-remote --heads origin refs/heads/${{ inputs.target_branch }})" >> $GITHUB_OUTPUT

      - name: Create the target branch
        if: steps.check_target_branch.ok == false
        shell: bash
        run: |
          git checkout --orphan ${{ inputs.target_branch }}
          git reset --hard
          git commit --allow-empty -m "Create target branch"
          git push origin ${{ inputs.target_branch }}

  build:
    name: Build the LaTeX document
    needs: [setup]
    runs-on: ubuntu-latest
    if: ${{
        github.event_name == 'pull_request' ||
        github.ref_name == 'current' ||
        (inputs.build_future_branches && startsWith(github.ref_name, 'future/'))
      }}
    permissions:
      contents: write
    steps:

      - name: Initialize
        uses: actions/checkout@v4

      - uses: kostrykin/build-latex-document-action@v2.2.0
        with:
          working_directory: ${{ inputs.working_directory }}
          document_filename: ${{ inputs.document_filename }}
          sources: ${{ inputs.sources }}
          target_branch: ${{ inputs.target_branch }}
