on:
  workflow_call:
    inputs:
      working_directory:
        required: true
        type: string
      document_filename:
        required: true
        type: string
      sources:
        required: true
        type: string
      build_future_branches:
        required: true
        type: boolean
      target_branch:
        type: string
        default: pdf

jobs:
  setup:
    name: Setup the target branch
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:

      - name: Initialize
        uses: actions/checkout@v4

      - name: Create the target branch
        shell: bash
        run: |
          git checkout --orphan ${{ inputs.target_branch }}
          git reset --hard

      - name: Add .nojekyll
        shell: bash
        run: |
          touch .nojekyll

      - name: Commit and push (fails silently if the branch already exists)
        if: steps.check_target_branch.ok == false
        uses: stefanzweifel/git-auto-commit-action@v5
        continue-on-error: true
        with:
          branch: ${{ inputs.target_branch }}
          commit_message: 'Create target branch'
          create_branch: true
          commit_options: '--allow-empty'
          skip_dirty_check: true

  build:
    name: Build the LaTeX document
    needs: [setup]
    runs-on: ubuntu-latest
    if: ${{
        github.event_name == 'pull_request' ||
        github.ref_name == 'current' ||
        (inputs.build_future_branches && startsWith(github.ref_name, 'future/'))
      }}
    permissions:
      contents: write
    steps:

      - name: Initialize
        uses: actions/checkout@v4

      - uses: kostrykin/build-latex-document-action@v2.2.0
        with:
          working_directory: ${{ inputs.working_directory }}
          document_filename: ${{ inputs.document_filename }}
          sources: ${{ inputs.sources }}
          target_branch: ${{ inputs.target_branch }}
