on:
  workflow_call:
    secrets:
      github-auth:
        required: true

jobs:
  post_pr_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - uses: kostrykin/report-test-coverage-action@v1.2.0
        with:
          github-auth: ${{ secrets.github-auth }}
