on:
  workflow_call:
    inputs:
      signature:
        required: false
        type: string
        default: '<!-- COVERAGE -->'

jobs:
  post_pr_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
      actions: read
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - uses: kostrykin/post-gh-comment-from-artifact-action@v1.0.2
        with:
          signature: ${{ inputs.signature }}
