on:
  workflow_call:
    secrets:
      github_token:
        required: false

jobs:
  post_pr_comment:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:

      - uses: kostrykin/build-latex-document-action@v2.2.0
        with:
          github_token: ${{ secrets.github_token }}
